name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          path: src

      - name: Setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Pack
        run: |
          mv ./src/pack.py ./pack.py
          python pack.py

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: dist

      - name: Get release information
        run: |
          VERSION=$(python -c "print(__import__('pack').__version__)")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

          LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          if [ -z "$LAST_TAG" ]; then
              CHANGELOG=$(git log --pretty=format:"- %s (%h)" --no-merges)
          else
              CHANGELOG=$(git log ${LAST_TAG}..HEAD --pretty=format:"- %s (%h)" --no-merges)
          fi

          echo "CHANGELOG<<EOF" >> $GITHUB_ENV
          echo "$CHANGELOG" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.ref_type == 'tag'
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          body: |
            已更新至 `v${{ env.VERSION }}`

            ## 更新日志

            ${{ env.CHANGELOG }}
          files: |
            dist/*
