name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v5
        with:
          path: src

      - name: Setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Pack
        run: |
          mv ./src/pack.py ./pack.py
          python pack.py

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: dist
