name: build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          path: src

      - name: Setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Pack
        run: |
          mv ./src/pack.py ./pack.py
          python pack.py

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: dist

      - name: Extract version
        run: |
          VERSION=$(python -c "print(__import__('pack').__version__)")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.ref_type == 'tag'
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          body: |
            更新至 `v${{ env.VERSION }}`
          files: |
            dist/*
