name: release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Extract version
        id: get_version
        run: |
          VERSION=$(python -c "print(__import__('pack').__version__)")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          body: |
            更新至 `v${{ env.VERSION }}`
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
